### ISSUE TITLE
Bedrock-demo-bouncer-stage.us-west.moz.works is down (tests on stage are failing)

### ISSUE THREAD

**Issue by stephendonner** [mozilla/stubattribution-tests#156]
The ```us-west deis 1``` cluster was decomissioned today, which likely was what took down the somewhat ephemeral https://bedrock-demo-bouncer-stage.us-west.moz.works/ instance.

@pmac - not urgent, but if it's easy, mind recreating/reprovisioning this?  I can easily change the BASE_URL we pass to pytest, too.

Thanks!

**Comment by jgmize** [comment]
@stephendonner can you clarify "somewhat ephemeral" for me please? How long do you think you'll need it? We can arrange for something more permanent if needed.

**Comment by jgmize** [comment]
I went ahead and rebased https://github.com/mozilla/bedrock/tree/demo/bouncer-stage on master; previously the last commit in that branch was Feb 16th, 118 commits behind master. I assumed based on the name that we needed to set `BOUNCER_URL=http://bouncer-bouncer.stage.mozaws.net` so I did that as well. The new demo is now deployed to https://bedrock-demo-bouncer-stage.oregon-b.moz.works

**Comment by stephendonner** [comment]
Let me know if you'd like a new, specific issue for that attribution_code KeyError.

**Comment by pmac** [comment]
@jgmize there were other settings on that instance needed for enabling stub attribution. Is there a backup of the us-west app settings somewhere I could look at?

**Comment by pmac** [comment]
@stephendonner and I just discussed it on IRC and we will just use stage (www.allizom.org) for this. We no longer need a special instance for these tests. I'll remove the new one in oregon-b shortly.

**Comment by stephendonner** [comment]
Thanks, you two.  For posterity, I've made the following changes on my end:

1) changed PYTEST_BASE_URL from https://bedrock-demo-bouncer-stage.us-west.moz.works to https://www.allizom.org, for https://qa-master.fxtest.jenkins.stage.mozaws.net/job/stubattribution.stage/
2) likewise, I've removed both the previous https://bedrock-demo-bouncer-stage.us-west.moz.works PYTEST_BASE_URL as well as the newer https://bedrock-demo-bouncer-stage.oregon-b.moz.works/, and replaced those two with the single, canonical https://www.allizom.org, as well

Cheers!
