### ISSUE TITLE
Assertion does not follow the pattern defined by style guide 

### ISSUE THREAD

**Issue by FannyVieira** [mozilla/stubattribution-tests#189]
In the style guide link, the recommended is:
`assert 'expected' == 'actual'  # good`
`assert 'actual' == 'expected'  #bad`
it's possible check more info in: [mozilla style guide](https://wiki.mozilla.org/QA/Execution/Web_Testing/Docs/Automation/StyleGuide)
https://github.com/mozilla/stubattribution-tests/blob/5738616403ac5b03ba9416644d9099e6cd56c7aa/tests/test_organic_flow.py#L47

**Comment by davehunt** [comment]
Thanks for spotting this @FannyVieira. Are you interested in providing a patch?

**Comment by FannyVieira** [comment]
Yes, i'm going to submit a pr
